file(GLOB SOURCES_CPP RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.cpp")
file(GLOB_RECURSE HEADERS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.h")
file(GLOB_RECURSE HEADERS_INL RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.inl")

if(CMAKE_HABILITATE_CUDA)
	file(GLOB SOURCES_CU RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.cu")
	file(GLOB_RECURSE HEADERS_CU RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} "*.cuh")
endif()

set(SOURCES ${SOURCES_CPP} ${SOURCES_ASM} ${SOURCES_CU} )
set(HEADERS ${HEADERS} ${HEADERS_CU} ${HEADERS_INL}  )